### ISSUE TITLE
Improve error handling for API key

### ISSUE THREAD

**Issue by seanmeehan** [cortexapps/cli#20]
While attempting to use the cli tool I noticed two issues that are related and could be improved.

Placing the API in double quotes like so
`[default]
api_key = "XXX"`

or providing an invalid API key will return blank output like this

`cortex catalog list

` 

It would be nice if key injection could trim the quotes and if we get a 403 the CLI tool would return a meaningful error

**Comment by jeff-schnitter** [comment]
Hey @seanmeehan -- thanks for creating the first issue for the CLI!

The following changes were pushed in version 0.9.0:
- if they exist, quotes are stripped off the beginning and end of the API key
- if an API call results in an error, the error reason from python requests will be posted to stderr
- if the error is a 401 (Unauthorized), a message like this will be displayed:
```
$ cortex teams list
Unauthorized

Check your api_key in /Users/myuser/.cortex/config.
```

**Comment by jeff-schnitter** [comment]
Completed in 0.9.0.

**Comment by jeff-schnitter** [comment]
Done.
